apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ${NAMESPACE}
spec:
  selector:
    app: cloud-config
  ports:
    - port: 9296
      targetPort: 9296
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
        - name: cloud-config
          image: ${REGISTRY}/cloud-config:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9296
          envFrom:
            - configMapRef:
                name: micro-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3