apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ${NAMESPACE}
  labels:
    app: favourite-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
        version: v1
    spec:
      containers:
      - name: favourite-service
        image: ${REGISTRY}/favourite-service:${IMAGE_TAG}
        ports:
        - containerPort: 8800
        envFrom:
          - configMapRef:
              name: micro-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8800
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8800
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: ${NAMESPACE}
  labels:
    app: favourite-service
spec:
  selector:
    app: favourite-service
  ports:
  - port: 8800
    targetPort: 8800
    protocol: TCP
  type: ClusterIP
