apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ${NAMESPACE}
  labels:
    app: order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      containers:
      - name: order-service
        image: ${REGISTRY}/order-service:${IMAGE_TAG}
        ports:
        - containerPort: 8300
        envFrom:
          - configMapRef:
              name: micro-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8300
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8300
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ${NAMESPACE}
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 8300
    targetPort: 8300
    protocol: TCP
  type: ClusterIP
