apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ${NAMESPACE}
  labels:
    app: shipping-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
        version: v1
    spec:
      containers:
      - name: shipping-service
        image: ${REGISTRY}/shipping-service:${IMAGE_TAG}
        ports:
        - containerPort: 8600
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: SPRING_ZIPKIN_BASE_URL
        - name: EUREKA_CLIENT_REGION
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: EUREKA_CLIENT_REGION
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: EUREKA_CLIENT_SERVICEURL_MYZONE
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: SPRING_CONFIG_IMPORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8600
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8600
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: ${NAMESPACE}
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
  - port: 8600
    targetPort: 8600
    protocol: TCP
  type: ClusterIP
