apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ${NAMESPACE}
  labels:
    app: user-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
      - name: user-service
        image: ${REGISTRY}/user-service:${IMAGE_TAG}
        ports:
        - containerPort: 8700
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: "http://service-discovery.${NAMESPACE}.svc.cluster.local:8761/eureka/"
        envFrom:
          - configMapRef:
              name: micro-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ${NAMESPACE}
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 8700
    targetPort: 8700
    protocol: TCP
  type: ClusterIP
